[server]
# Configurações para otimizar o Streamlit Cloud
fileWatcherType = "none"
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 1024  # 1GB em MB

[browser]
gatherUsageStats = false

[global]
developmentMode = false

[theme]
base = "light"
